package com.aimia.endeavour.member;

import com.aimia.endeavour.validation.*;
import function com.aimia.endeavour.validation.ValidationHelper.error;
import function com.aimia.endeavour.validation.ValidationHelper.warning;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

#global ReferenceDataService refService;
global ValidationReport validationReport;
global ReportFactory reportFactory;

rule "Member name is never Gadaffi"
	when
		Member( name == "gadaffi" )
	then 
		LoggerFactory.getLogger("MemberRules.drl").debug("Gadaffi rule called");
		error(kcontext);
end


